### ISSUE TITLE
Unable to Load Pre Trained Checkpoint for evaluation

### ISSUE THREAD

**Issue by TimHunt12** [ayanban011/SwinDocSegmenter#4]
I have set up the repo as explained in the ReadMe and Install instructions.  I had to modify the Yaml files for the Output Directory to get it to make the right directories.

When I run the CLI command to download the pre trained model weights from the Model Zoo I get an error. 

For others PLEASE NOTE that the `--config-file maskdino_R50_bs16_50ep_4s_dowsample1_2048.yaml` doesn't find the YAML fille unless you provide the full path to it from the repo code in the CLI.

```
python ./train_net.py \
    --config-file maskdino_R50_bs16_50ep_4s_dowsample1_2048.yaml \
    --eval-only \
    --num-gpus 1 \
    MODEL.WEIGHTS ./model_final.pth
```

For some reason the command can't find the checkpoint.  It runs through all the configurations and displays a great deal in the logging, but in the end it gives the following error.

```
[11/08 21:52:44 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from ./model_final.pth ...
[11/08 21:52:44 fvcore.common.checkpoint]: [Checkpointer] Loading from ./model_final.pth ...
Traceback (most recent call last):
  File "/home/ubuntu/git/doc_segmenter/./train_net.py", line 392, in <module>
    launch(
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "/home/ubuntu/git/doc_segmenter/./train_net.py", line 360, in main
    DetectionCheckpointer(model, save_dir=cfg.OUTPUT_DIR).resume_or_load(
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/fvcore/common/checkpoint.py", line 227, in resume_or_load
    return self.load(path, checkpointables=[])
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 62, in load
    ret = super().load(path, *args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/fvcore/common/checkpoint.py", line 153, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint ./model_final.pth not found!
```
I don't know if the author of this repo removed the checkpoint or just provided the wrong information to get it.

I went to Model Zoo and there is no repo listed for SwinDocSegmenter.

Has anyone gotten past this point?

**Comment by ayanban011** [comment]
Did you try by downloading the weights and given the proper path from the command line?? Also check the naming convention,  which is model_final_{dataset_name}_swindocseg.pth.

Dataset_name = prima, doclay, publay, etc.

**Comment by TimHunt12** [comment]
Yes I tried to do it from the command line, but it failed to find the checkpoint file and download the weights.  When you say proper path I am assuming you are referring to the path you listed in the Readme.

```
python ./train_net.py \
    --config-file maskdino_R50_bs16_50ep_4s_dowsample1_2048.yaml \
    --eval-only \
    --num-gpus 1 \
    MODEL.WEIGHTS ./model_final.pth
```

**Comment by TimHunt12** [comment]
Thanks that will help to know that I need to modify that.  I'll try that.  Thanks.

**Comment by TimHunt12** [comment]
Ok I added to the CLI 
`./model_final_doclay_swindocseg.pth`
I still got the following errror.

```
[11/09 15:41:51 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from ./model_final_doclay_swindocseg.pth ...
[11/09 15:41:51 fvcore.common.checkpoint]: [Checkpointer] Loading from ./model_final_doclay_swindocseg.pth ...
Traceback (most recent call last):
  File "/home/ubuntu/git/doc_segmenter/./train_net.py", line 392, in <module>
    launch(
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "/home/ubuntu/git/doc_segmenter/./train_net.py", line 360, in main
    DetectionCheckpointer(model, save_dir=cfg.OUTPUT_DIR).resume_or_load(
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/fvcore/common/checkpoint.py", line 227, in resume_or_load
    return self.load(path, checkpointables=[])
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 62, in load
    ret = super().load(path, *args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/fvcore/common/checkpoint.py", line 153, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint ./model_final_doclay_swindocseg.pth not found!
```

Do I first need to manually download the model from the Model Zoo area of the Readme and put it on my linux server before I run the CLI command?

If so do I need to put it in a specific directory or just at the root of the repo?

**Comment by TimHunt12** [comment]
I apologize if I am not following your instructions very well.

**Comment by ayanban011** [comment]
Yes you need to download the model manually and put it into the folder from where you are running train_net.py

**Comment by TimHunt12** [comment]
That worked. I got a new error, but I'll put that in a new ticket.  Your instruction worked for the checkpoint so if it ok with you I'll close this ticket.
