### ISSUE TITLE
Datasets Train: and Test: not Loading in Step 3

### ISSUE THREAD

**Issue by TimHunt12** [ayanban011/SwinDocSegmenter#5]
After I configure a linux server, install all the libraries, download the mode from the model zoo, and then run the command under "Step 3: For testing our model, download the best pretrained model weights from the Model Zoo" in the Readme. 

I always get a KeyError: "Dataset 'pub_val' is not registered! ...

This is the same if you use PubLayNet or DocLayNet.  All of the available datasets are for image instance segmentation for objects not document content.

```
Available datasets are: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_valminusminival, coco_2017_train, coco_2017_val, coco_2017_test, coco_2017_test-dev, coco_2017_val_100, keypoints_coco_2014_train, keypoints_coco_2014_val, keypoints_coco_2014_minival, keypoints_coco_2014_valminusminival, keypoints_coco_2017_train, keypoints_coco_2017_val, keypoints_coco_2017_val_100, coco_2017_train_panoptic_separated, coco_2017_train_panoptic_stuffonly, coco_2017_train_panoptic, coco_2017_val_panoptic_separated, coco_2017_val_panoptic_stuffonly, coco_2017_val_panoptic, coco_2017_val_100_panoptic_separated, coco_2017_val_100_panoptic_stuffonly, coco_2017_val_100_panoptic, lvis_v1_train, lvis_v1_val, lvis_v1_test_dev, lvis_v1_test_challenge, lvis_v0.5_train, lvis_v0.5_val, lvis_v0.5_val_rand_100, lvis_v0.5_test, lvis_v0.5_train_cocofied, lvis_v0.5_val_cocofied, cityscapes_fine_instance_seg_train, cityscapes_fine_sem_seg_train, cityscapes_fine_instance_seg_val, cityscapes_fine_sem_seg_val, cityscapes_fine_instance_seg_test, cityscapes_fine_sem_seg_test, cityscapes_fine_panoptic_train, cityscapes_fine_panoptic_val, voc_2007_trainval, voc_2007_train, voc_2007_val, voc_2007_test, voc_2012_trainval, voc_2012_train, voc_2012_val, ade20k_sem_seg_train, ade20k_sem_seg_val, ade20k_full_sem_seg_train, ade20k_full_sem_seg_val, ade20k_panoptic_train, ade20k_panoptic_val, coco_2017_train_stuff_10k_sem_seg, coco_2017_test_stuff_10k_sem_seg, mapillary_vistas_sem_seg_train, mapillary_vistas_sem_seg_val, coco_2017_train_panoptic_with_sem_seg, coco_2017_val_panoptic_with_sem_seg, ade20k_instance_train, ade20k_instance_val, mapillary_vistas_panoptic_train, mapillary_vistas_panoptic_val, prima_train, prima_val"

```
Detectron2 doesn't have the instance segmentation datasets for doclay or publay.  

Below is the error that always comes up.  How do we get the right datasets for train and test?

```
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/detectron2/data/catalog.py", line 51, in get
    f = self[name]
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/collections/__init__.py", line 1106, in __getitem__
    raise KeyError(key)
KeyError: 'pub_val'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/git/doc_segmenter/./train_net.py", line 392, in <module>
    launch(
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "/home/ubuntu/git/doc_segmenter/./train_net.py", line 367, in main
    res = Trainer.test(cfg, model)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/detectron2/engine/defaults.py", line 604, in test
    data_loader = cls.build_test_loader(cfg, dataset_name)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/detectron2/engine/defaults.py", line 560, in build_test_loader
    return build_detection_test_loader(cfg, dataset_name)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/detectron2/config/config.py", line 207, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/detectron2/config/config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/detectron2/data/build.py", line 562, in _test_loader_from_config
    dataset = get_detection_dataset_dicts(
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/detectron2/data/build.py", line 253, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/detectron2/data/build.py", line 253, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/detectron2/data/catalog.py", line 53, in get
    raise KeyError(
KeyError: "Dataset 'pub_val' is not registered! Available datasets are: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_valminusminival, coco_2017_train, coco_2017_val, coco_2017_test, coco_2017_test-dev, coco_2017_val_100, keypoints_coco_2014_train, keypoints_coco_2014_val, keypoints_coco_2014_minival, keypoints_coco_2014_valminusminival, keypoints_coco_2017_train, keypoints_coco_2017_val, keypoints_coco_2017_val_100, coco_2017_train_panoptic_separated, coco_2017_train_panoptic_stuffonly, coco_2017_train_panoptic, coco_2017_val_panoptic_separated, coco_2017_val_panoptic_stuffonly, coco_2017_val_panoptic, coco_2017_val_100_panoptic_separated, coco_2017_val_100_panoptic_stuffonly, coco_2017_val_100_panoptic, lvis_v1_train, lvis_v1_val, lvis_v1_test_dev, lvis_v1_test_challenge, lvis_v0.5_train, lvis_v0.5_val, lvis_v0.5_val_rand_100, lvis_v0.5_test, lvis_v0.5_train_cocofied, lvis_v0.5_val_cocofied, cityscapes_fine_instance_seg_train, cityscapes_fine_sem_seg_train, cityscapes_fine_instance_seg_val, cityscapes_fine_sem_seg_val, cityscapes_fine_instance_seg_test, cityscapes_fine_sem_seg_test, cityscapes_fine_panoptic_train, cityscapes_fine_panoptic_val, voc_2007_trainval, voc_2007_train, voc_2007_val, voc_2007_test, voc_2012_trainval, voc_2012_train, voc_2012_val, ade20k_sem_seg_train, ade20k_sem_seg_val, ade20k_full_sem_seg_train, ade20k_full_sem_seg_val, ade20k_panoptic_train, ade20k_panoptic_val, coco_2017_train_stuff_10k_sem_seg, coco_2017_test_stuff_10k_sem_seg, mapillary_vistas_sem_seg_train, mapillary_vistas_sem_seg_val, coco_2017_train_panoptic_with_sem_seg, coco_2017_val_panoptic_with_sem_seg, ade20k_instance_train, ade20k_instance_val, mapillary_vistas_panoptic_train, mapillary_vistas_panoptic_val, prima_train, prima_val"
```

**Comment by ayanban011** [comment]
Check line no. 350 and 351 of train_net.py
Change prima_train/prima_val with your desired dataset name.
got to the config file you are using.
and put the following
DATASETS:
  TRAIN: ("put the same training dataset name you are using in train_net.py",) 
  TEST: ("put the same validation dataset name you are using in train_net.py",)

**Comment by TimHunt12** [comment]
Thanks I'll try that out.

**Comment by TimHunt12** [comment]
Thanks again @ayanban011. It worked so I am closing the issue if that is ok.
